name: CI

on: [push]

jobs:
    mac-testing:
        name: CI - Test compilation + loading errors / MacOS
        runs-on: mac
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 12/10
              uses: actions/setup-node@v1
              with:
                version: [12, 10]
            - name: "Install dependencies"
              run: "npm i -g uglify-js uglifyjs;"
            - name: "Generate output"
              run: "node bundle-it.js;"
            - name: "Check out.js"
              run: "node out.js;"
            - name: "Check out.min.js"
              run: "node out.min.js;"
    ubuntu-testing:
        name: CI - Test compilation + loading errors / Ubuntu Latest
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 12/10
              uses: actions/setup-node@v1
              with:
                version: [12, 10]
            - name: "Install dependencies"
              run: "npm i -g uglify-js uglifyjs;"
            - name: "Generate output"
              run: "node bundle-it.js;"
            - name: "Check out.js"
              run: "node out.js;"
            - name: "Check out.min.js"
              run: "node out.min.js;"
              
